### PR TITLE
CSS selectors demo

### PR DESCRIPTION
**Pull request by mikkrieg**
Here is what I have for the revamp of the CSS Selectors Demo. Let me know if any more content/explanation/editing is necessary. I've also added the demo to the demo grid so that it can be accessed from there.

### CODE REVIEW

**Review by JenniferYu8 — COMMENTED** [review]
I love the interactive section! Here are a few suggestions:

- You might want to consider switching the order of the sections so that the instructions come before the practice part
- In the classes & IDs section, you mention class "first-p" and id "second-p" while the text shown says ".blue-p" and "#red-p"
- I'm not sure if it's something on my end (sass has been acting wonky recently), but it seems like the demo doesn't have much styling; the instructions section in particular resembles a sea of text. It might be a good idea to add some colour (e.g. when you show the syntax for YOUR_SELECTOR { YOUR_STYLINGS; }, class= CLASS_NAME, id= ID_NAME) if you haven't already, to make it more appealing and to make it easier to see the key points. 
- On the note of styling, would it be possible to make the iframe take up the entire div section's space?

Overall, I really like where the demo is headed! The explanations of the selectors, classes, and IDs are very clear and informative. If you have already styled it and it's just my computer that's not working, please let me know so that we can have a quick meet to see where you're at. Otherwise, with a few small changes, this will definitely be an amazing demo! Good job!!!

**Comment by mikkrieg** [comment]
@JenniferYu8 I checked out your suggestions and made some fixes! 

- I switched the order of the content and put the editor and Iframe at the bottom
- I edited the text errors regarding the examples
- The Iframe now takes up the full div space and is underneath the code editor

I also realized that I when I copied over the old lesson, I kept writing my stylings in css file instead of the scss file. I've moved it all over to the scss and compiled the css with it. Hopefully that fixes the error with you not being able to see the stylings.

**Review by JenniferYu8 — COMMENTED** [review]
Looking good! A few things to keep in mind:

- It might just be on my side, but the h2 tag "Practice" appears on the same line as the Review note
- Try adding a few bit by bots to make the instructions less text-heavy
- If possible, give the editor some colour

Overall, this demo is really coming along. Keep up the great work!

**Comment by mikkrieg** [comment]
@JenniferYu8 I've made some more fixes!

- Added color to the code jar
- Added some bit by bots throughout the lesson
- Fixed the positioning error with the h2 "practice" heading 

Let me know if you find any issues or if I should add something else!

**Comment by JenniferYu8** [comment]
The codejar editor looks great! Also, loving the bit by bots!!! A few suggestions:

- Give the code format parts a monospace font ('Anonymous Pro', monospace) so that it's easier to recognize that code should look like that
- In the classes and ID's section, refer to the bit by bots as bit by bots and not robots
- Instead of having the review section (the red text), try adding the syntax of classes and IDs to the actual explanation. On that note, it might be cool if you created a table to compare the syntax & functions of classes and IDs.
- Try separating the Practice section from the information section and try putting the editor and iframe side-by-side (using the flex-box and flex-col classes). It might make the page's layout more interesting.

With these final changes, the demo should be ready! Good job!

**Comment by mikkrieg** [comment]
@JenniferYu8 I've reviewed your suggestions and made some changes!

- I gave the code snippets in the lesson the monospace font 
- Made sure to refer to the bit by bots with their correct name
- Separated the practice section and put the editor and iframe side by side
- I incorporated how to create classes and ID's into the lesson 

I didn't create a table for ID's and Classes. My reasoning is that it didn't feel necessary since I think that the lessons explain the differences between classes and id's with enough detail, without taking the focus of the lesson away from css-selectors. But if you'd like me to create a table going further into classes and id's, I can totally go ahead and do that.

**Comment by mikkrieg** [comment]
@JenniferYu8 Sorry for taking so long to get this done. I have separated the Classes and ID's section from the What is a Selector section. Let me know if anything else needs to be done!

**Comment by mikkrieg** [comment]
@JenniferYu8 Alrighty I've added the table and I like how it looks! Definitely makes the demo less text heavy. Let me know what you think and if any more changes need to be made,

**Comment by mikkrieg** [comment]
@JenniferYu8 I've made the code in the tables monospace, let me know if any other changes need to be made

**Review by JenniferYu8 — APPROVED** [review]
Awesome!

**Pull request merged**
